### ISSUE TITLE
The Ultra weight is missing in both condensed and compressed versions.

### ISSUE THREAD

**Issue by atheistray** [bBoxType/FiraSans#18]
Not sure if it's intentional. Both the condensed and compressed versions include the heavy weights, but neither has the ultra weights. You haven't updated this repository for a while. I hope everything is all right?

**Comment by carrois** [comment]
Hi Ray. 

This is intended. 
The Ultra weight was experimental from the beginning – meaning that we didn’t have full control on the outlines because they were extrapolated (boldest Master is lighter than "Ultra"). For the normal width, the results of this extrapolation were not too bad but for the Condensed and Compressed, it doesn’t reach the quality we‘re looking for. That’s why there are only 15 weights for Condensed and Compressed (ans their Italics).

Concerning the update question:
There will be a 4.3 soon, with collected smaller fixes/improvements and a lot of localized features (Bulgarian, Hungarian, etc.) But this will be the last version if Fira Sans, future developments will be implemented in a new branch of Fira. More soon!
