### ISSUE TITLE
The characters became thinner and lower

### ISSUE THREAD

**Issue by atheistray** [bBoxType/FiraSans#2]
I'm using fira as the system fonts on my rooted Android 4.4 phone. I noticed some differences in this new release: the characters seem to go down a bit and they become slightly thinner.
This is the regular weight from last release on opera browser:
![screenshot_2016-10-18-22-19-36](https://cloud.githubusercontent.com/assets/22341522/19483258/5b271c3e-9519-11e6-8d02-832d094eb28f.jpg)
This is the new release. Notice the gap between those suggestions and URLs, and the letter g and y on the keyboard. The characters look slightly thinner.
![screenshot_2016-10-18-22-25-26](https://cloud.githubusercontent.com/assets/22341522/19483424/ec505432-9519-11e6-810a-4a3e2abf5707.jpg)
The same thing happened to light weight too. It became less legible.
![screenshot_2016-10-18-22-33-18](https://cloud.githubusercontent.com/assets/22341522/19483499/2cf61152-951a-11e6-97ba-6a0ab136be5a.jpg)
![screenshot_2016-10-18-22-46-50](https://cloud.githubusercontent.com/assets/22341522/19483514/3990b4d0-951a-11e6-84da-01402edd9c89.jpg)
Finally, the new ligatures (ff, ft,...) are not working.

**Comment by carrois** [comment]
Thanks for reporting.
We’re discussing your issues internally, let me get back to you tomorrow in detail. 
Which version of Fira did you use before (your 1st screenshots)?

**Comment by atheistray** [comment]
The ttf files from the last release from Mozilla. https://github.com/mozilla/Fira/releases/tag/4.202

**Comment by carrois** [comment]
All your concerns except from the ligature issue are probably export and/or auto hinting issues, we had some changes within the routine. Give us some time to.

The ligatures with 2 glyphs should work fine. Are you sure whether "dlig" feature is enabled in your browser? Ligatures from 3 glyphs (ffj, ffl, ffj, fft) don’t work for the Upright files, see issue #3
Will be updated soon.

**Comment by atheistray** [comment]
I think maybe they're export issues rather than hinting, because Google says Android doesn't implement hinting. I'm not sure though. My browser doesn't enable discretionary ligatures by default, so it doesn't show new ligatures.

**Comment by carrois** [comment]
Can you write an email to fira@carrois.com?
We would like to send you test files, if that’s ok with you.
Thanks for your cooperation.

**Comment by atheistray** [comment]
Sure, I just sent one. I'm Ray. The weights I usually use are regular, light, thin, medium and their italic variants. (TTF) I don't mind trying more weights though.

**Comment by carrois** [comment]
Ray, thanks again for your cooperation. Please have a look at the new version, should be fine. Can you confirm?

**Comment by atheistray** [comment]
Yes, I can confirm both problems with the height and hinting are solved. However, new ligatures are still not showing. Are they intended to be used only as discretionary ligatures?

**Comment by atheistray** [comment]
The only working ligatures are fi and fl.

**Comment by carrois** [comment]
> Are they intended to be used only as discretionary ligatures?

Yes

**Comment by atheistray** [comment]
But shouldn't they be standard ligatures? I thought discretionary ligatures were those such as st, ct, et, etc (haha).

**Comment by BonnEconLab** [comment]
Indeed, in many other fonts—such as Minion Pro and Calibri, but also Meta and Meta Serif—the “f” ligatures are all treated as standard ligatures (lig), as atheistray pointed out. Hence, I also expected the new Fira “f” ligatures to be coded as standard ligatures.

**Comment by carrois** [comment]
I general, there is no consistent rule which ligatures should be standard an which discretionary. It depends on the design.

Our initial thought was to make the additional ligatures of the new release optional by putting them into dlig-feature. Like that, there won’t be any change in consisting designs. If somebody likes to see the new ligatures, he/she should switch on the dlig feature. But this way might be a bit too easy, you are right here. 

So we delved into the topic and want to share our conclusions. You are invited to discuss further.

A problem of defining all new ligatures as standard could be the fact that some designers increase leading of the typeface. A lot of ligatures wouldn’t be good in this case. (On the other hand, they would not want to have standard ligatures as well because these would be way too narrow. So they would probably switch off both features, liga and dlig). So in fact, there might be no problem here...

Also, we think that the opinion of easyaspi314 in the original discussion is quite reasonable: Let’s not create ligatures where they are not necessary.
https://github.com/mozilla/Fira/issues/53

So our question is: which ligatures are necessary and which ones are optional (in particular for Fira)? As necessary we defined only clashes. 

Fira is a huge system with all Sans fonts coming out of 8-Master files. Regarding this large range of widths and weights, it might happen that a ligature is not necessary in most of the widths/weights but it is indeed necessary in few widths/weights. But the features have to work for each of the final fonts.
We did some testing and came to the conclusion that you can find a necessity for each of the new ligatures (often only in the fat weights). Thus, we decided to put them all into liga (standard) with the next update.

In addition, there will be a contextual alternate f (with a longer or shorter top) in combination with ascender letters like h, k, etc. So to say another way of solving clash problems.
